#ifndef LIBSTL_THUMB_H
#define LIBSTL_THUMB_H

/* Generated by cbindgen from src/lib.rs. Do not edit by hand, see cbindgen.toml. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Allows utilizing `stl-thumb` from C-like languages
 *
 * This function renders an image of the file `model_filename_c` and stores it into the buffer `buf_ptr`.
 *
 * You must provide a memory buffer large enough to store the image. Images are written in 8-bit RGBA format,
 * so the buffer must be at least `width`*`height`*4 bytes in size. `model_filename_c` is a pointer to a C string with
 * the file path.
 *
 * Returns `true` if succesful and `false` if unsuccesful.
 *
 * # Example in C
 * ```c
 * const char* model_filename_c = "3DBenchy.stl";
 * uint32_t width = 256;
 * uint32_t height = 256;
 *
 * size_t img_size = (size_t)width * height * 4;
 * uint8_t* buf_ptr = malloc(img_size);
 *
 * bool success = render_to_buffer(buf_ptr, width, height, model_filename_c);
 * ```
 *
 * # Safety
 *
 * * `buf_ptr` _must_ point to a valid initialized buffer, at least `width * height * 4` bytes long.
 * * `model_filename_c` must point to a valid null-terminated string.
 */
bool render_to_buffer(uint8_t *buf_ptr,
                      uint32_t width,
                      uint32_t height,
                      const char *model_filename_c);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIBSTL_THUMB_H */
